import { Property } from './supabase';

export const dummyProperties: Array<Property & { latitude?: string; longitude?: string; map_link?: string; whatsapp_number?: string }> = [
  {
    id: 'demo-1',
    user_id: 'user-1',
    seller_name: 'Chaminda Perera',
    seller_avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    title: 'Cozy Family House with Garden',
    description:
      'A charming 3 bedroom family house with a spacious garden and modern amenities. Located close to schools and shops.',
    price: 25000000,
    category: 'house',
    listing_type: 'sale',
    location: 'Near Lakeview',
    city: 'Colombo',
    district: 'Colombo',
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1800,
    contact_number: '+94 77 123 4567',
    is_featured: true,
    is_active: true,
    views_count: 124,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latitude: '6.9271',
    longitude: '79.8612',
    map_link: 'https://www.google.com/maps?q=6.9271,79.8612',
    whatsapp_number: '+94 771234567',
    property_images: [
      {
        id: 'img-1-1',
        property_id: 'demo-1',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: true,
        display_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-1-2',
        property_id: 'demo-1',
        image_url: 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 2,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-1-3',
        property_id: 'demo-1',
        image_url: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 3,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-1-4',
        property_id: 'demo-1',
        image_url: 'https://images.pexels.com/photos/1069805/pexels-photo-1069805.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 4,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'demo-2',
    user_id: 'user-2',
    seller_name: 'Nadeesha Fernando',
    seller_avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
    title: 'Modern Apartment in City Center',
    description:
      'Bright 2 bedroom apartment with balcony and city views. Walking distance to public transport and restaurants.',
    price: 8500000,
    category: 'annex',
    listing_type: 'sale',
    location: 'City Center',
    city: 'Kandy',
    district: 'Kandy',
    bedrooms: 2,
    bathrooms: 1,
    area_sqft: 850,
    contact_number: '+94 77 987 6543',
    is_featured: false,
    is_active: true,
    views_count: 58,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latitude: '7.2906',
    longitude: '80.6337',
    map_link: 'https://www.google.com/maps?q=7.2906,80.6337',
    whatsapp_number: '+94 779876543',
    property_images: [
      {
        id: 'img-2-1',
        property_id: 'demo-2',
        image_url: 'https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: true,
        display_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-2-2',
        property_id: 'demo-2',
        image_url: 'https://images.pexels.com/photos/37347/house-home-interior-design-decoration-37347.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 2,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-2-3',
        property_id: 'demo-2',
        image_url: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 3,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'demo-3',
    user_id: 'user-3',
    seller_name: 'Ruwan Silva',
    seller_avatar: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=200',
    title: 'Large Commercial Lot',
    description: 'Perfect plot for development, well connected and zoned for commercial use.',
    price: 42000000,
    category: 'commercial',
    listing_type: 'sale',
    location: 'Industrial Zone',
    city: 'Galle',
    district: 'Galle',
    bedrooms: 0,
    bathrooms: 0,
    area_sqft: 10000,
    contact_number: '+94 71 555 1212',
    is_featured: false,
    is_active: true,
    views_count: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latitude: '6.0323',
    longitude: '80.2168',
    map_link: 'https://www.google.com/maps?q=6.0323,80.2168',
    whatsapp_number: '+94 715551212',
    property_images: [
      {
        id: 'img-3-1',
        property_id: 'demo-3',
        image_url: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: true,
        display_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-3-2',
        property_id: 'demo-3',
        image_url: 'https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 2,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'demo-4',
    user_id: 'user-4',
    seller_name: 'Priya Jayasinghe',
    seller_avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=200',
    title: 'Cozy Room for Rent',
    description: 'Affordable single room suitable for students or working professionals.',
    price: 25000,
    category: 'room',
    listing_type: 'rent',
    location: 'Near University',
    city: 'Matara',
    district: 'Matara',
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 300,
    contact_number: '+94 71 222 3333',
    is_featured: false,
    is_active: true,
    views_count: 86,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    latitude: '5.9487',
    longitude: '80.5350',
    map_link: 'https://www.google.com/maps?q=5.9487,80.5350',
    whatsapp_number: '+94 712223333',
    property_images: [
      {
        id: 'img-4-1',
        property_id: 'demo-4',
        image_url: 'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: true,
        display_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'img-4-2',
        property_id: 'demo-4',
        image_url: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1400',
        is_primary: false,
        display_order: 2,
        created_at: new Date().toISOString(),
      },
    ],
  },
];

export default dummyProperties;
